logo: # add logo name
title: Sophie Sparrow
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://sophisparrow.co.nz" # the base hostname & protocol for your site, e.g. http://example.com

# Banner settings
video: test2.mp4 # add banner video. Add your video file to the folder video
banner-title: # add banner title
banner-desc: # add banner description

# Author settings
author-pic: face.jpg # your photo
author-name: Sophie Sparrow # your name
about-author: Sophie’s first stage role was that of a flea. She was 8 years old when her principal selected her for this part in the school production. Her passion for the stage and singing had begun. 
Whangarei soprano, Sophie began her vocal training with Lisa Rangi at age 9 and at 14 she embarked on her classical singing journey with the great opera diva herself, Joan Kennaway (QSM). Joan opened Sophie’s heart and mind to the world of opera. While training with Joan, she attained her ATCL with distinction (2009).
Sophie was a member of Opera North, performing in the annual Opera in the Garden 2007 – 2010, and other Opera North fundraisers and showcases. While in Whangarei, Sophie performed musical theatre roles – Gabriella in Sweet Pea Production’s High School Musical, Aida in WTC’s CATS, and Candy in WTC’s Buddy Holly: The Buddy Holly Story.
Moving to Dunedin, Sophie completed a Bachelor of Music with first class honors in Classical Voice Performance (2014) under the tutelage of Isabel Cunningham and Frances Wilson, and Bachelor of Commerce in Accounting (2016) from the University of Otago. She is also an alumnus of the NZ Opera School (2017) and IFAC Handa NZ Singing School (2011).
Currently training with Frances Wilson at the Auckland Opera Studio, Sophie has been selected for prestigious competitions and programmes. Last year she was hand-picked to attend the inaugural Dame Malvina Major Foundation (DMMF) Opera Studies programme, in association with New Zealand Opera. She was a finalist in the annual NZ Aria Competition, performing with maestro Johannes Fritzsch and the Auckland Philharmonia Orchestra. In 2016, Sophie was selected as one of only 10 Lexus Song Quest Semi-finalists, one of New Zealand’s premier competitions, working intensively with international judge Yvonne Kenny, and coaches Terence Dennis and Catherine Norton in a week-long workshop concluding with the semifinalist concert nationally broadcast on RNZ.
Sophie has placed in many regional competitions, most notable being 3rd in the Napier DMMF Aria (2018) and Christchurch DMMF Aria (2017), 2nd in Wellington DMMF Aria (2016), 3rd in the National Young Performer Awards (2016), 2nd in the Hamilton Singing Competition Norah Howell Award (2017) and 2nd in Dunedin DMMF Aria (2015).
Recent performances include guest artist for Opera North’s Opera in the Garden 2018 at Operacardo Whangarei, performing in the Dame Malvina Major Foundation Summerset Concert Series, soloist at the AYO Baroque Concert Series, a member of NZ Opera’s Freemasons Chorus for Carmen, soloist for Mozart Great Mass in C Minor, and soloist for Mendelssohn’s Hymn of Praise.
Sophie’s operatic roles include Pamina in Opera Otago’s The Magic Flute (2015) and the University of Otago The Magic Flute (2014), and Barbarina in Opera Otago’s The Marriage of Figaro (2012). 
December 2017 Sophie auditioned for Masters Programmes at the UK’s most prestigious Music Conservatoires. She has been awarded a partial scholarship at the Royal College of Music for tuition fees. This year, Sophie has also received an Opera North scholarship, and is supported by the Auckland Opera Studio. 
 # about author
email: your-email@domain.com # your email
phone: (496)-169-6557 # your pnone number
website: https://dwayne.example.com # you website

# Social link
google_url:    # add url link
#twitter_url:   # add url link
instagram_url: # add url link
#pinterest_url: # add url link
#dribbble_url:  # add url link
facebook_url: https://www.facebook.com/sophiesparrowsoprano # add url link

# Disqus
#discus_identifier: mr-brown # add your discus identifier

# Newsletter
mailchimp: # add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Tracker
analytics:

# Paginate
paginate: 12
paginate_path: /page:num/

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
